### PR TITLE
Refactored agents, made them standalone with embedded platform.js & stackTrace.js

### PR DESCRIPTION
**Pull request by NathanGloyn**
I have refactored the native client:
- made function an IIFE with correct namespace so runs when loaded
- enable non-blocking logging
- ability to indicate if should propagate the OnError i.e. call existing OnError
- embed Platform.js so that the script isn't required

Need to update the wiki to specify that this script must be loaded after any other script the user has which uses onError otherwise we may not actually receive the error if the existing handler doesn't propagate it.

Note: this still requires the end user to have stackTrace.js althougth I am looking to see if I can remove that dependency as well :)

### CODE REVIEW

**Comment by DaveSussman** [comment]
There's an error on Line 5, which has:

window.printStackTrace = StackTrace();

StackTrace() doesn't exist.

Without that line, the javascript agent works fine, but we also need changes to the angular one, as this depends upon the global 'platform'. The easy solution for this is to expose platform from the vanilla javascript agent:

```
gibraltar.agent = {
    log: log,
    propagateOnError: propagateOnError,
    platform: Platform()
};
```

The angular agent then hooks into this in the platformService:

return ({
            platform: gibraltar.agent.platform
        });

With those two changes in place it seems to be working fine.

**Comment by NathanGloyn** [comment]
I wouldn't recommend doing that, the platform.js was only added to the vanilla JS as an optimisation.

If the angular agent needs platform.js then I would recommend it requiring it.

I mistakenly thought the angular agent was its own implementation built using angular idioms, but it is really just an adapter around the native agent then we may need to take a different route to do this.

**Comment by NathanGloyn** [comment]
I removed that line, it was included incorrectly, part of the work looking at embedding stackTrace.js. I've pushed an updated to the branch so should be good now.

**Comment by NathanGloyn** [comment]
I've now added Tests project (using jasmine) and have found and fixed some obvious & some not so obvious issues with the agents.

Both agents now are standalone and have embedded versions of platform.js and stackTrace.js

**Pull request merged**
